modLoader = "javafml"
loaderVersion = "[32,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "rad"
version = "${version}"
displayName = "Reload Audio Driver"
authors = "CJMinecraft01, JayJay1989BE"
description = '''
Reloads the audio driver when pressing F3 + R.
'''
logoFile = "assets/rad/logo.png"

[[dependencies.rad]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rad]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rad]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.63,)"
ordering = "AFTER"
side = "BOTH"